name: Daily Run with Nix Environment

on:
  schedule:
      # Runs daily at 7:00 GMT-03.
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      USERNAME: ${{ secrets.REDDIT_PASSWORD }}
      PASSWORD: ${{ secrets.REDDIT_USERNAME }}
      SUB_REDDIT: ${{ vars.REDDIT_SUB}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo Target
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install Nix with Flakes Enabled
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Verify Nix Installation
        run: nix --version

      - name: Build the project
        run: |
          nix develop .#devShells.x86_64-linux.default --command bash -c "
            cargo build --release
          "

      - name: Run reddit-badges
        run: |
          nix develop .#devShells.x86_64-linux.default --command bash -c "
            ./target/release/reddit-badges \
              --client-id '$CLIENT_ID' \
              --client-secret '"$CLIENT_SECRET' \
              --username '$USERNAME' \
              --password '$PASSWORD' \
              --subreddit '$SUBREDDIT'
