name: Daily Run

on:
  schedule:
      # Runs daily at 7:00 GMT-03.
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  daily-job:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      USERNAME: ${{ secrets.REDDIT_PASSWORD }}
      PASSWORD: ${{ secrets.REDDIT_USERNAME }}
      SUB_REDDIT: ${{ vars.REDDIT_SUB}}

    steps:
     - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build 
        run: cargo build --release

      - name: Run reddit-badges
        run: |
          ./target/release/reddit-badges \
              --client-id '$CLIENT_ID' \
              --client-secret '$CLIENT_SECRET' \
              --username '$USERNAME' \
              --password '$PASSWORD' \
              --subreddit '$SUB_REDDIT'
