name: Daily Run

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  daily-job:
    runs-on: ubuntu-latest
    environment: runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Run reddit-badges
        env:
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          USERNAME: ${{ secrets.REDDIT_USERNAME }}
          PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          SUB_REDDIT: ${{ vars.REDDIT_SUB }}
        run: |
          ./target/release/reddit-badges \
            --client-id "$CLIENT_ID" \
            --client-secret "$CLIENT_SECRET" \
            --username "$USERNAME" \
            --password "$PASSWORD" \
            --subreddit "$SUB_REDDIT"

